In [1]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

plt.style.use('fivethirtyeight')

%matplotlib inline

# Reading the data

In [2]:
data = pd.read_csv('winequality-white.csv', sep = ';')
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

# Implementing the Solution

## Adding an extra Column

In [3]:
X = np.append(arr = np.ones((X.shape[0], 1)), values = X, axis = 1)

## Splitting the data

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

## Scaling the data

In [5]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [6]:
X_train

array([[ 0.        , -0.30163255, -0.8763441 , ...,  2.19191607,
         2.44784257, -0.08630365],
       [ 0.        ,  0.05768519, -0.47688247, ..., -0.5257906 ,
        -1.92220009,  0.72839366],
       [ 0.        , -0.42140512, -0.57674787, ..., -0.92350377,
         0.08801954, -0.81953122],
       ...,
       [ 0.        , -2.33776636,  0.67156971, ...,  0.33592127,
        -0.785989  , -0.33071284],
       [ 0.        ,  0.29723034, -0.77647869, ...,  0.07077916,
        -1.13559241,  1.21721204],
       [ 0.        , -0.78072285,  0.22217538, ..., -1.453788  ,
        -0.61118729,  1.3801515 ]])

In [7]:
X_test

array([[ 0.00000000e+00,  1.37518354e+00, -1.77286247e-01, ...,
        -6.58361657e-01,  2.01083831e+00,  8.91333117e-01],
       [ 0.00000000e+00,  4.17002918e-01, -1.27580572e+00, ...,
         2.19191607e+00, -1.74183024e-01, -4.12182566e-01],
       [ 0.00000000e+00,  1.97404642e+00, -7.76478689e-01, ...,
        -1.25493141e+00, -1.22299326e+00, -4.83391502e-03],
       ...,
       [ 0.00000000e+00, -7.80722855e-01, -6.76613282e-01, ...,
         2.03350214e-01,  6.18682871e-04, -4.93652296e-01],
       [ 0.00000000e+00, -1.14004059e+00,  1.22309974e-01, ...,
         4.68492328e-01, -6.98588143e-01, -7.38061487e-01],
       [ 0.00000000e+00,  1.77457764e-01,  1.22309974e-01, ...,
         1.37064685e-01,  8.80195361e-02,  7.28393657e-01]])

## Linear regression

In [8]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)
predictions = regressor.predict(X_test)

In [9]:
predictions

array([6.21618955, 5.70705751, 5.78851024, ..., 5.80910474, 5.61464719,
       6.07871637])

In [10]:
y_test

1060    7
2011    5
3179    4
2060    5
2664    7
       ..
3610    5
1437    7
4426    6
933     5
3626    5
Name: quality, Length: 1225, dtype: int64